---
name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v2

    - name: Test
      run: |
        go clean -testcache
        go test -race -coverprofile=coverage.out -covermode=atomic ./... -v

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
